name: CentrallslesCore
version: '${project.version}'
main: me.superbility.centrallslescore.Main
depend:
  - Quests
  - PlaceholderAPI
commands:
  centralcore:
    usage: /<command>
    description: Main command
    permission: centralcore.admin